# Generated by Django 5.2.17 on 2026-09-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=160)),
                ('commodity', models.CharField(max_length=100)),
                ('min_quantity_kg', models.FloatField()),
                ('max_quantity_kg', models.FloatField()),
                ('quality', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=120)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=60)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('quality', models.CharField(max_length=80)),
                ('origin', models.CharField(max_length=120)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_on', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('SOLD', 'Sold')], default='OPEN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_quantity', models.FloatField(default=0)),
                ('observed_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=160)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market_api.lot')),
            ],
        ),
    ]
